---
name: Codespell

on:
  push:
    branches: [master,next]
  pull_request:
    branches: [master,next]

jobs:
  codespell:
    name: Check for typos
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run codespell
        uses: codespell-project/actions-codespell@v2
        # this file contains typos by design
        skip: acl-evil.lst
